version: 2
jobs:
  lint-and-test:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint test
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - lint-and-test
      - deploy:
          requires:
            - lint-and-test
          filters:
            branches:
              only:
                - master
